import MainNavbar from '../../MainNavbar/MainNavbar';
import Head from 'next/head';

export interface NavbarLayoutProps {
  children: React.ReactNode;
}

export const NavbarLayout = ({ children }: NavbarLayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainNavbar />
      {children}
      <footer>
        <h1>footer</h1>
      </footer>
    </>
  );
};

export default NavbarLayout;
