import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Ir a los repositorios</h1>
        <Link href="/repository" >Navegar </Link>

      </main>

      <footer >
        <h1>footer</h1>
      </footer>
    </div>
  )
}


